apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: "{{ .Release.Name }}-role"
  namespace: {{ .Release.Namespace }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}-serviceaccount"
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: "{{ .Release.Name }}-rolebinding"
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: "{{ .Release.Name }}-role"
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: "{{ .Release.Name }}-serviceaccount"
  namespace: {{ .Release.Namespace }}
